"use client";

import { useEffect, useState } from "react";
import { api, ApiError } from "@/lib/api";
import { useProject } from "@/lib/project-context";
import { GeneratedReport } from "@/lib/types";
import { PageHeader, EmptyState } from "@/components/ui/PageHeader";
import { DataTable } from "@/components/ui/DataTable";
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { Badge } from "@/components/ui/Badge";

export default function ReportsPage() {
  const { selectedProject, loading: projectLoading } = useProject();
  const [reports, setReports] = useState<GeneratedReport[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  async function load() {
    if (!selectedProject) return setLoading(false);
    setLoading(true);
    try {
      const data = await api.get<GeneratedReport[]>(`/api/v1/projects/${selectedProject.id}/reports`);
      setReports(data);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedProject]);

  async function generate(reportType: "weekly_status" | "risk_summary") {
    if (!selectedProject) return;
    setGenerating(reportType);
    setError(null);
    try {
      await api.post(`/api/v1/projects/${selectedProject.id}/reports`, { report_type: reportType });
      await load();
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Failed to generate report");
    } finally {
      setGenerating(null);
    }
  }

  if (projectLoading || loading) return <p className="text-sm text-slate-400">Loading…</p>;

  if (!selectedProject) {
    return <EmptyState title="No project selected" description="Select a project from the top bar first." />;
  }

  return (
    <div>
      <PageHeader
        title="Executive Reporting"
        description="DOT-ready PDF reports with AI-generated executive narratives."
      />

      <div className="mb-6 grid grid-cols-1 gap-4 md:grid-cols-2">
        <Card>
          <h3 className="mb-1 text-sm font-semibold text-federal-950">Weekly Status Report</h3>
          <p className="mb-3 text-xs text-slate-500">
            RFIs, submittals, risks, NCRs, safety, schedule, and cost KPIs with an executive summary.
          </p>
          <Button onClick={() => generate("weekly_status")} disabled={generating !== null}>
            {generating === "weekly_status" ? "Generating…" : "Generate Weekly Status Report"}
          </Button>
        </Card>
        <Card>
          <h3 className="mb-1 text-sm font-semibold text-federal-950">Risk Summary Report</h3>
          <p className="mb-3 text-xs text-slate-500">Open risks ranked by score with an AI risk posture narrative.</p>
          <Button onClick={() => generate("risk_summary")} disabled={generating !== null}>
            {generating === "risk_summary" ? "Generating…" : "Generate Risk Summary Report"}
          </Button>
        </Card>
      </div>

      {error && <p className="mb-4 text-sm text-status-poor">{error}</p>}

      <DataTable<GeneratedReport>
        rows={reports}
        emptyTitle="No reports generated yet"
        columns={[
          { header: "Title", render: (r) => <span className="font-medium text-federal-950">{r.title}</span> },
          { header: "Type", render: (r) => <Badge label={r.report_type} tone="blue" /> },
          { header: "Generated By", render: (r) => r.generated_by || "—" },
          { header: "Date", render: (r) => new Date(r.created_at).toLocaleString() },
          {
            header: "",
            render: (r) => (
              <a
                href={api.fileUrl(`/api/v1/projects/${selectedProject.id}/reports/${r.id}/pdf`)}
                target="_blank"
                rel="noreferrer"
                className="text-xs font-semibold text-federal-700 hover:text-federal-900"
              >
                ⬇ Download PDF
              </a>
            ),
          },
        ]}
      />
    </div>
  );
}
